name: binary build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-15, ubuntu-24.04-arm, macos-15-intel, windows-latest]
        build_type: [Release]
        staticcompile: [ON, OFF]

    steps:
    - uses: actions/checkout@v4
      with:
        path: project
        submodules: 'true'
    - name: Build project
      run: |
        cd project
        mkdir -p build && cd build
        cmake -DSTATICCOMPILE=${{ matrix.staticcompile }} -S ..
        cmake --build . --config ${{matrix.build_type}} -v

    - name: Upload Artifact - LinuxAMD64
      if: contains(matrix.os, 'ubuntu') && matrix.staticcompile == 'ON' && !contains(matrix.os, 'arm')
      uses: actions/upload-artifact@v4
      with:
        name: breakid-linux-x86_64
        path: project/build/breakid

    - name: Upload Artifact - LinuxARM64
      if: contains(matrix.os, 'ubuntu') && matrix.staticcompile == 'ON' && contains(matrix.os, 'arm')
      uses: actions/upload-artifact@v4
      with:
        name: breakid-linux-arm64
        path: project/build/breakid

    - name: Upload Artifact - Mac ARM64
      if: contains(matrix.os, 'macos-15') && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: breakid-mac-arm64
        path: project/build/breakid

    - name: Upload Artifact - Mac-intel
      if: contains(matrix.os, 'macos-15-intel') && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: breakid-mac-x86_64-intel
        path: project/build/breakid

    - name: Upload Artifact - Windows
      if: contains(matrix.os, 'windows') && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: breakid-win64.exe
        path: project\build\Release\breakid.exe
